### ISSUE TITLE
go2rtc v1.9.4 adds streaming network graph in DOT format

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/Blog#24]
New feature in latest release:

<img width="981" alt="network" src="https://github.com/AlexxIT/Blog/assets/511909/d0eec804-12f1-4ca6-a06c-c037d35d547a">

**go2rtc.yaml**

```yaml
streams:
  rtsp-dahua1: rtsp://admin:***@192.168.10.90/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  rtsp-tplink1: rtsp://admin:***@192.168.10.91/stream1
  rtsp-sonoff1: rtsp://admin:***@192.168.10.93/av_stream/ch0
  http-reolink1: http://192.168.10.92/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=***
  tapo1: tapo://***@192.168.10.91:8800
  homekit-g3:
    - homekit://192.168.10.30:12345?client_id=***&client_private=***&device_id=***&device_public=***
    - ffmpeg:homekit-g3#audio=aac#audio=opus
```
