### ISSUE TITLE
Howto SSH to HassOS

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/Blog#3]
**ATTENTION!** By using these instructions you agree not to ask for support from Hass community for your current Hass installation.

## Local way

[USB drive](https://developers.home-assistant.io/docs/operating-system/debugging/)

## Remote way

1. Install [SSH addon](https://my.home-assistant.io/redirect/supervisor_addon/?addon=a0d7b954_ssh&repository_url=https%3A%2F%2Fgithub.com%2Fhassio-addons%2Frepository)
2. Add your key to addon config
   ```yaml
   username: root
   authorized_keys:
   - ssh-rsa AASDJKJKJFWJFAFLCNALCMLAK234234.....
   ```
3. Disable addon **Protection mode** option
4. Open addon **Web UI**
   ```bash
   ~ cp /etc/ssh/authorized_keys /share
   ~ docker run -it --rm -v /root:/mnt/root -v /mnt/data/supervisor/share:/mnt/share bash cp /mnt/share/authorized_keys /mnt/root/.ssh
   ~ rm /share/authorized_keys
   ~ ha host reboot
   ```

Thats all. Now you have:

- SSH on port 22 - addon
- SSH on port 22222 - hassio host
